### ISSUE TITLE
Tool doesn't find subdomains?

### ISSUE THREAD

**Issue by bugzymalone** [Cillian-Collins/subscraper#12]
The issue is a bit vague, I know. But I've installed all the dependencies:

pip3 install -r reqs.txt

The tool appears to run 'ok' but it never seems to return subdomains. I've run it against many popular websites with no results.
From Kali: 

python3 ./subscraper.py -u www.youtube.com -v

It just hangs for a few seconds (this time varies) and then drops back to shell.

I'm not in a position to troubleshoot it further at the moment but just wanted to make sure I'm not doing anything silly?

**Comment by bugzymalone** [comment]
For the record, the -o option seems to work ok, the results just don't display when I want it to on the screen.

**Comment by Cillian-Collins** [comment]
You will have to replace ``www.youtube.com`` with ``youtube.com``

It's trying to find subdomains of ``*.www.youtube.com`` which is returning nothing.

**Comment by Cillian-Collins** [comment]
Let me know if that works for you.
