### ISSUE TITLE
No module named 'Colour_Console' Error!

### ISSUE THREAD

**Issue by Xeek3y** [Cillian-Collins/subscraper#13]
Hello i'm trying to use your script in kali linux but i'm getting this error:
https://i.imgur.com/av8xqct.png
```
Traceback (most recent call last):
  File "subscraper.py", line 8, in <module>
    from Colour_Console import ctext
ModuleNotFoundError: No module named 'Colour_Console'
```
I installed the requirements and also tried installing the modules manually with the commands like these:
```
pip3 install colour_console
pip3 install colored
```
etc,  but i'm still getting this error! what can cause this issue?

**Comment by Cillian-Collins** [comment]
``pip install -r requirements.txt``

This is the command that should be ran, can also run pip3. It seems like you're installing this with pip3 and then running it using python2 though.

Try ``python3 subscraper.py``

**Comment by DanHacksAll** [comment]
> `pip install -r requirements.txt`
> 
> This is the command that should be ran, can also run pip3. It seems like you're installing this with pip3 and then running it using python2 though.
> 
> Try `python3 subscraper.py`

Traceback (most recent call last):
  File "subscraper.py", line 8, in <module>
    from Color_Console import ctext
  File "/usr/local/lib/python2.7/dist-packages/Color_Console/__init__.py", line 1, in <module>
    from Color_Console.Color_Console import *
  File "/usr/local/lib/python2.7/dist-packages/Color_Console/Color_Console.py", line 190
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/Color_Console/Color_Console.py on line 191, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I have this error, i try differents ways, but nothing work, i really don't know what's the problem....

**Comment by Xeek3y** [comment]
> 
> 
> `pip install -r requirements.txt`
> 
> This is the command that should be ran, can also run pip3. It seems like you're installing this with pip3 and then running it using python2 though.
> 
> Try `python3 subscraper.py`


lol i tried everything already that you said and yeah i've installed python 2 as well as python 3 so i already did whatever you said and also googled for every possible solution but nothing seems to be working for me :/

**Comment by Cillian-Collins** [comment]
@Danx01 The stack trace is for Python 2, that means you're running it in Python 2.7 whereas this is a Python 3 project.

@Xeek3y Have you managed to run other Python 3 programs? Post the stack trace, if it's a Python 2.7 issue, then that's the problem. You need to run it as python 3, that should be something like ``python3 subscaper.py -v -u youtube.com``

**Comment by Xeek3y** [comment]
> 
> 
> @Danx01 The stack trace is for Python 2, that means you're running it in Python 2.7 whereas this is a Python 3 project.
> 
> @Xeek3y Have you managed to run other Python 3 programs? Post the stack trace, if it's a Python 2.7 issue, then that's the problem. You need to run it as python 3, that should be something like `python3 subscaper.py -v -u youtube.com`

Hello well yeah i ran it through python3 and this issue is now fixed, what i did was i renamed the module folder from `Colour_Console` to `Color_Console` and now i'm not getting any error and the script is working fine but this script is a bit slow and also it will be good if you add bulk domain scanning and import results in one file, Ex: import the domains from `domains.txt` file and extract subdomains one by one from all the domains js files :)

**Comment by Cillian-Collins** [comment]
Glad it's working, seems like a weird problem. If I get more time I'll come back to this project and add stuff like that, it's a relatively easy thing to add anyway.

**Comment by DanHacksAll** [comment]
The program works, everything perfectly, I think my pc is crazy, sorry for the inconvenience and thanks for this great program: D
