### ISSUE TITLE
Some Colour Issue

### ISSUE THREAD

**Issue by yadavmayank742** [Cillian-Collins/subscraper#3]
On running with Python2 : 
`[yadav@0x2E6]─[~/recon_tools/subscraper]$ python subscraper.py -u redacted.com`
I get this output : 
`Traceback (most recent call last):`
  `File "subscraper.py", line 6, in <module> from Color_Console import ctext`
  `File "/usr/local/lib/python2.7/dist-packages/Color_Console/__init__.py", line 1, in <module> from Color_Console.Color_Console import *`
  `File "/usr/local/lib/python2.7/dist-packages/Color_Console/Color_Console.py", line 190
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/Color_Console/Color_Console.py on line 191, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`
`[✗]─[yadav@0x2E6]─[~/recon_tools/subscraper]$ `

`==================================================================`

On running with Python3, 

`[yadav@0x2E6]─[~/recon_tools/subscraper] $python3 subscraper.py -u redacted.com`
The O/P was : 
`Traceback (most recent call last):`
  `File "subscraper.py", line 6, in <module> from Color_Console import ctext`
`ModuleNotFoundError: No module named 'Color_Console'`
`[✗]─[yadav@0x2E6]─[~/recon_tools/subscraper]`

**Comment by yadavmayank742** [comment]
Fix :


Use `pip3` insted of `pip` in
 `pip install -r requirements.txt`

and

Run with `python3` instead of `python` in
 `python subscraper.py -u domain.com -o output.txt`

**Comment by Cillian-Collins** [comment]
This is not an issue with the project but moreover an issue with your installation. You are running both Python2 and Python3, therefore ``pip`` and ``python`` are both pointed at Python2 instead of Python3. You will have this issue running any Python3 project.
