### ISSUE TITLE
error detected

### ISSUE THREAD

**Issue by rajeshk28** [Cillian-Collins/subscraper#6]
Getting the below error, I tried with python, python2, and python3 and tried installing requirements with pip and pip3 as well.

Traceback (most recent call last):
  File "subscraper.py", line 166, in <module>
    main()
  File "subscraper.py", line 159, in main
    find_scripts(args.u)
  File "subscraper.py", line 50, in find_scripts
    soup = BeautifulSoup(r.text, 'lxml')
  File "/usr/local/lib/python3.7/dist-packages/bs4/__init__.py", line 198, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by Cillian-Collins** [comment]
You're missing the ``lxml`` module. It's in the requirements.txt file so it should be working.

Try the following command and let me know the response:

``pip3 install lxml``

**Comment by rajeshk28** [comment]
I have already installed all the requirements with pip and pip3

Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (4.5.0)

**Comment by Cillian-Collins** [comment]
This is a python3 project so it will need to be in python 3.

There may be conflicts if you are running several instances of python. You could also try uninstalling and reinstalling it.

**Comment by rajeshk28** [comment]
uninstalling and reinstalling python3 or subscraper?

sorry, this is silly question, i researched but didnt got concrete answer. If I have installed this tool then how we can uninstall it? do we simply have to delete the folder?

**Comment by Cillian-Collins** [comment]
It's a problem with lxml. Subscraper is trying to access lxml module but it can't find it. You should try uninstalling/reinstalling lxml.

**Comment by rajeshk28** [comment]
Thanks for your help.
I troubleshoot some issues and got the resolution by

sudo pip3 install --upgrade beautifulsoup4 html5lib spry

**Comment by Cillian-Collins** [comment]
That's good to hear. Let me know if you have any other issues.
